apiVersion: v1
kind: Service
metadata:
  name: influx
spec:
  ports:
  - port: 8086
  selector:
    app: influx
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: influx-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: influx
spec:
  selector:
    matchLabels:
      app: influx
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: influx
    spec:
      containers:
      - image: influxdb
        name: influx
        env:
        - name: INFLUXDB_DB
          value: {{ .Params.INFLUXDB_DB }}
        ports:
        - containerPort: 8086
          name: api
        volumeMounts:
        - name: influx-persistent-storage
          mountPath: /var/lib/influxdb
        livenessProbe:
          httpGet:
            path: /ping
            port: api
          initialDelaySeconds: 30
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ping
            port: api
          initialDelaySeconds: 5
          timeoutSeconds: 1
      volumes:
      - name: influx-persistent-storage
        persistentVolumeClaim:
          claimName: influx-pvc
