apiVersion: batch/v1
kind: Job
metadata:
  namespace: default
  name: {{ .PlanName }}-job
spec:
  template:
    metadata:
      name: {{ .PlanName }}-job
    spec:
      restartPolicy: OnFailure
      containers:
      - name: {{ .PlanName }}
        image: influx
        imagePullPolicy: IfNotPresent
        command:
        - /bin/sh
        - -c
        - "influxd restore -portable -db  {{ .Params.INFLUXDB_DB }} /backups"
        volumeMounts:
        - name: backup-pv
          mountPath: /backups
      volumes:
      - name: backup-pv
        persistentVolumeClaim:
          claimName: {{ .Name }}-backup-pv
